[tool.poetry]
name = "fin-statement-model"
version = "0.1.0"
description = ""
authors = ["Jon Eickmeier <me@jeickmeier.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.26.4"
pandas = "^2.1.4"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
