METRIC_DEFINITIONS = {
    # Profitability Metrics
    "gross_profit": {
        "inputs": ["revenue", "cost_of_goods_sold"],
        "formula": "revenue - cost_of_goods_sold",
        "metric_type": "profitability",
        "metric_description": "The profit a company makes after deducting the costs directly associated with making and selling its products or services.",
    },
    "operating_income": {
        "inputs": ["gross_profit", "operating_expenses"],
        "formula": "gross_profit - operating_expenses",
        "metric_type": "profitability",
        "metric_description": "Profit generated from core business operations, excluding interest and taxes.",
    },
    "total_interest_expense": {
        "inputs": ["other_interest_expenses", "interest_income", "interest_expense"],
        "formula": "interest_income - interest_expense-other_interest_expenses",
        "metric_type": "profitability",
        "metric_description": "Income generated from interest-bearing assets minus interest expenses.",
    },
    "pre_tax_income": {
        "inputs": ["operating_income", "total_interest_expense"],
        "formula": "operating_income + total_interest_expense",
        "metric_type": "profitability",
        "metric_description": "Profit before taxes.",
    },
    "net_income": {
        "inputs": ["pre_tax_income", "tax_expense"],
        "formula": "pre_tax_income - tax_expense",
        "metric_type": "profitability",
        "metric_description": "The company's total earnings or profit after all expenses, interest, and taxes have been deducted.",
    },
    "ebit": {
        "inputs": ["net_income", "tax_expense", "total_interest_expense"],
        "formula": "net_income - total_interest_expense + tax_expense",
        "metric_type": "profitability",
        "metric_description": "Earnings Before Interest and Taxes; measures company's operating performance without considering financial and tax-related decisions.",
    },
    "ebitda": {
        "inputs": ["ebit", "depreciation_and_amortization"],
        "formula": "ebit + depreciation_and_amortization",
        "metric_type": "profitability",
        "metric_description": "Earnings Before Interest, Taxes, Depreciation, and Amortization; indicates operational performance excluding non-cash expenses.",
    },
    "nopat": {
        "inputs": ["net_income", "total_interest_expense"],
        "formula": "net_income - total_interest_expense",
        "metric_type": "profitability",
        "metric_description": "Net Operating Profit After Taxes; shows operating performance after tax adjustments but before financing costs.",
    },
    # Margin Metrics
    "gross_profit_margin": {
        "inputs": ["gross_profit", "revenue"],
        "formula": "gross_profit / revenue",
        "metric_type": "margin",
        "metric_description": "Percentage of revenue remaining after deducting cost of goods sold; indicates pricing strategy and production efficiency.",
    },
    "operating_margin": {
        "inputs": ["operating_income", "revenue"],
        "formula": "operating_income / revenue",
        "metric_type": "margin",
        "metric_description": "Percentage of revenue remaining after operating expenses; measures operational efficiency.",
    },
    "net_profit_margin": {
        "inputs": ["net_income", "revenue"],
        "formula": "net_income / revenue",
        "metric_type": "margin",
        "metric_description": "Percentage of revenue that becomes profit after all expenses; indicates overall profitability.",
    },
    "ebit_margin": {
        "inputs": ["ebit", "revenue"],
        "formula": "ebit / revenue",
        "metric_type": "margin",
        "metric_description": "Operating profitability as a percentage of revenue before interest and taxes.",
    },
    "ebitda_margin": {
        "inputs": ["ebitda", "revenue"],
        "formula": "ebitda / revenue",
        "metric_type": "margin",
        "metric_description": "Operating performance as a percentage of revenue before financial, tax, and non-cash items.",
    },
    "nopat_margin": {
        "inputs": ["nopat", "revenue"],
        "formula": "nopat / revenue",
        "metric_type": "margin",
        "metric_description": "After-tax operating profit as a percentage of revenue.",
    },
    # Asset Metrics
    "average_total_assets": {
        "inputs": ["total_assets", "total_assets_previous"],
        "formula": "(total_assets + total_assets_previous) / 2",
        "metric_type": "asset",
        "metric_description": "Mean value of assets between two periods; used for various return calculations.",
    },
    "average_shareholders_equity": {
        "inputs": ["total_equity", "total_equity_previous"],
        "formula": "(total_equity + total_equity_previous) / 2",
        "metric_type": "asset",
        "metric_description": "Mean value of shareholders' equity between two periods; used for return calculations.",
    },
    # Return Metrics
    "return_on_assets": {
        "inputs": ["net_income", "average_total_assets"],
        "formula": "net_income / average_total_assets",
        "metric_type": "return",
        "metric_description": "Measures how efficiently a company uses its assets to generate profits.",
    },
    "return_on_equity": {
        "inputs": ["net_income", "average_shareholders_equity"],
        "formula": "net_income / average_shareholders_equity",
        "metric_type": "return",
        "metric_description": "Measures how efficiently a company uses shareholders' investments to generate profits.",
    },
    "temp_debt_equity": {
        "inputs": ["total_debt", "total_equity"],
        "formula": "total_debt + total_equity",
        "metric_type": "return",
        "metric_description": "Temporary calculation for invested capital computation.",
    },
    "invested_capital": {
        "inputs": ["total_debt", "total_equity", "cash"],
        "formula": "total_debt + total_equity - cash",
        "metric_type": "return",
        "metric_description": "Total investment in the business excluding excess cash; used for ROIC calculation.",
    },
    "roic": {
        "inputs": ["nopat", "average_invested_capital"],
        "formula": "nopat / average_invested_capital",
        "metric_type": "return",
        "metric_description": "Return on Invested Capital; measures how efficiently a company uses all capital to generate profits.",
    },
    "capital_employed": {
        "inputs": ["total_assets", "current_liabilities"],
        "formula": "total_assets - current_liabilities",
        "metric_type": "return",
        "metric_description": "Long-term capital invested in the business; used for ROCE calculation.",
    },
    "roce": {
        "inputs": ["ebit", "average_capital_employed"],
        "formula": "ebit / average_capital_employed",
        "metric_type": "return",
        "metric_description": "Return on Capital Employed; measures profitability relative to long-term financing.",
    },
    # Liquidity Metrics
    "current_ratio": {
        "inputs": ["current_assets", "current_liabilities"],
        "formula": "current_assets / current_liabilities",
        "metric_type": "liquidity",
        "metric_description": "Measures company's ability to pay short-term obligations with short-term assets.",
    },
    "quick_assets": {
        "inputs": ["current_assets", "inventory"],
        "formula": "current_assets - inventory",
        "metric_type": "liquidity",
        "metric_description": "Most liquid assets; used in quick ratio calculation.",
    },
    "quick_ratio": {
        "inputs": ["quick_assets", "current_liabilities"],
        "formula": "quick_assets / current_liabilities",
        "metric_type": "liquidity",
        "metric_description": "More conservative measure of liquidity that excludes inventory from current assets.",
    },
    "cash_ratio": {
        "inputs": ["cash", "current_liabilities"],
        "formula": "cash / current_liabilities",
        "metric_type": "liquidity",
        "metric_description": "Most conservative liquidity measure; shows ability to cover short-term debt with cash only.",
    },
    # Leverage Metrics
    "debt_to_equity": {
        "inputs": ["total_debt", "total_shareholders_equity"],
        "formula": "total_debt / total_shareholders_equity",
        "metric_type": "leverage",
        "metric_description": "Measures extent of debt financing relative to equity financing.",
    },
    "debt_to_assets": {
        "inputs": ["total_debt", "total_assets"],
        "formula": "total_debt / total_assets",
        "metric_type": "leverage",
        "metric_description": "Indicates percentage of assets financed through debt.",
    },
    "interest_coverage": {
        "inputs": ["ebit", "interest_expense"],
        "formula": "ebit / interest_expense",
        "metric_type": "leverage",
        "metric_description": "Indicates ability to meet interest payments from operating earnings.",
    },
    "financial_leverage": {
        "inputs": ["average_total_assets", "average_shareholders_equity"],
        "formula": "average_total_assets / average_shareholders_equity",
        "metric_type": "leverage",
        "metric_description": "Measures total assets relative to shareholders' equity; indicates leverage level.",
    },
    "equity_multiplier": {
        "inputs": ["total_assets", "total_equity"],
        "formula": "total_assets / total_equity",
        "metric_type": "leverage",
        "metric_description": "Alternative measure of financial leverage; shows assets funded by each dollar of equity.",
    },
    # Debt Service Metrics
    "cash_available_for_debt_service": {
        "inputs": ["operating_cash_flow", "interest_expense", "taxes"],
        "formula": "operating_cash_flow + interest_expense + taxes",
        "metric_type": "debt_service",
        "metric_description": "Cash available to service debt obligations after operations.",
    },
    "debt_service_coverage_ratio": {
        "inputs": ["cash_available_for_debt_service", "debt_service"],
        "formula": "cash_available_for_debt_service / debt_service",
        "metric_type": "debt_service",
        "metric_description": "Measures ability to service debt obligations from operating cash flow.",
    },
    "ebit_plus_fixed_charges": {
        "inputs": ["ebit", "fixed_charges_before_tax"],
        "formula": "ebit + fixed_charges_before_tax",
        "metric_type": "debt_service",
        "metric_description": "Operating earnings plus fixed charges; used in fixed charge coverage ratio.",
    },
    "fixed_charge_coverage_ratio": {
        "inputs": ["ebit", "fixed_charges_before_tax", "fixed_charges"],
        "formula": "(ebit + fixed_charges_before_tax) / fixed_charges",
        "metric_type": "debt_service",
        "metric_description": "Measures ability to meet fixed payment obligations from earnings.",
    },
    # Efficiency Metrics
    "asset_turnover": {
        "inputs": ["revenue", "average_total_assets"],
        "formula": "revenue / average_total_assets",
        "metric_type": "efficiency",
        "metric_description": "Measures how efficiently assets are used to generate revenue.",
    },
    "inventory_turnover": {
        "inputs": ["cost_of_goods_sold", "average_inventory"],
        "formula": "cost_of_goods_sold / average_inventory",
        "metric_type": "efficiency",
        "metric_description": "Indicates how many times inventory is sold and replaced over a period.",
    },
    "receivables_turnover": {
        "inputs": ["revenue", "average_accounts_receivable"],
        "formula": "revenue / average_accounts_receivable",
        "metric_type": "efficiency",
        "metric_description": "Measures how quickly customers pay their bills.",
    },
    "payables_turnover": {
        "inputs": ["cost_of_goods_sold", "average_accounts_payable"],
        "formula": "cost_of_goods_sold / average_accounts_payable",
        "metric_type": "efficiency",
        "metric_description": "Measures how quickly the company pays its suppliers.",
    },
    # Working Capital Metrics
    "ar_over_revenue": {
        "inputs": ["average_accounts_receivable", "revenue"],
        "formula": "(average_accounts_receivable / revenue) * 365",
        "metric_type": "working_capital",
        "metric_description": "Proportion of receivables to revenue; used in DSO calculation.",
    },
    "dso": {
        "inputs": ["average_accounts_receivable", "revenue"],
        "formula": "(average_accounts_receivable / revenue) * 365",
        "metric_type": "working_capital",
        "metric_description": "Days Sales Outstanding; average number of days to collect payment.",
    },
    "inv_over_cogs": {
        "inputs": ["average_inventory", "cost_of_goods_sold"],
        "formula": "(average_inventory / cost_of_goods_sold) * 365",
        "metric_type": "working_capital",
        "metric_description": "Proportion of inventory to COGS; used in DIO calculation.",
    },
    "dio": {
        "inputs": ["average_inventory", "cost_of_goods_sold"],
        "formula": "(average_inventory / cost_of_goods_sold) * 365",
        "metric_type": "working_capital",
        "metric_description": "Days Inventory Outstanding; average days to sell inventory.",
    },
    "ap_over_cogs": {
        "inputs": ["average_accounts_payable", "cost_of_goods_sold"],
        "formula": "(average_accounts_payable / cost_of_goods_sold) * 365",
        "metric_type": "working_capital",
        "metric_description": "Proportion of payables to COGS; used in DPO calculation.",
    },
    "dpo": {
        "inputs": ["average_accounts_payable", "cost_of_goods_sold"],
        "formula": "(average_accounts_payable / cost_of_goods_sold) * 365",
        "metric_type": "working_capital",
        "metric_description": "Days Payables Outstanding; average days to pay suppliers.",
    },
    "temp_dso_dio": {
        "inputs": ["dso", "dio"],
        "formula": "dso + dio",
        "metric_type": "working_capital",
        "metric_description": "Temporary calculation for cash conversion cycle.",
    },
    "cash_conversion_cycle": {
        "inputs": ["temp_dso_dio", "dpo"],
        "formula": "temp_dso_dio - dpo",
        "metric_type": "working_capital",
        "metric_description": "Number of days to convert resource inputs into cash flows.",
    },
    # Asset Utilization Metrics
    "working_capital_turnover": {
        "inputs": ["revenue", "average_working_capital"],
        "formula": "revenue / average_working_capital",
        "metric_type": "asset_utilization",
        "metric_description": "Measures how efficiently working capital is used to generate sales.",
    },
    "fixed_asset_turnover": {
        "inputs": ["revenue", "average_net_fixed_assets"],
        "formula": "revenue / average_net_fixed_assets",
        "metric_type": "asset_utilization",
        "metric_description": "Measures how efficiently fixed assets are used to generate sales.",
    },
    # Market Metrics
    "eps": {
        "inputs": ["net_income", "shares_outstanding"],
        "formula": "net_income / shares_outstanding",
        "metric_type": "market",
        "metric_description": "Earnings Per Share; profit allocated to each outstanding share.",
    },
    "p_e_ratio": {
        "inputs": ["share_price", "eps"],
        "formula": "share_price / eps",
        "metric_type": "market",
        "metric_description": "Price-to-Earnings ratio; indicates market value relative to earnings.",
    },
    "p_s_ratio": {
        "inputs": ["market_capitalization", "revenue"],
        "formula": "market_capitalization / revenue",
        "metric_type": "market",
        "metric_description": "Price-to-Sales ratio; indicates market value relative to revenue.",
    },
    "ev_ebitda": {
        "inputs": ["enterprise_value", "ebitda"],
        "formula": "enterprise_value / ebitda",
        "metric_type": "market",
        "metric_description": "Enterprise Value to EBITDA; indicates company value relative to operating performance.",
    },
    "ev_ebit": {
        "inputs": ["enterprise_value", "ebit"],
        "formula": "enterprise_value / ebit",
        "metric_type": "market",
        "metric_description": "Enterprise Value to EBIT; indicates company value relative to operating earnings.",
    },
    # Dividend Metrics
    "dividends_per_share": {
        "inputs": ["annual_dividends", "shares_outstanding"],
        "formula": "annual_dividends / shares_outstanding",
        "metric_type": "dividend",
        "metric_description": "Total dividends paid divided by number of shares outstanding.",
    },
    "dividend_yield": {
        "inputs": ["dividends_per_share", "share_price"],
        "formula": "dividends_per_share / share_price",
        "metric_type": "dividend",
        "metric_description": "Dividend return relative to share price.",
    },
    "dividend_payout_ratio": {
        "inputs": ["dividends", "net_income"],
        "formula": "dividends / net_income",
        "metric_type": "dividend",
        "metric_description": "Proportion of earnings paid out as dividends.",
    },
    # Cash Flow Metrics
    "free_cash_flow": {
        "inputs": ["operating_cash_flow", "capex"],
        "formula": "operating_cash_flow - capex",
        "metric_type": "cash_flow",
        "metric_description": "Cash available after operating expenses and capital investments.",
    },
    "p_fcf": {
        "inputs": ["market_capitalization", "free_cash_flow"],
        "formula": "market_capitalization / free_cash_flow",
        "metric_type": "cash_flow",
        "metric_description": "Price to Free Cash Flow; indicates market value relative to cash generation.",
    },
    "ev_sales": {
        "inputs": ["enterprise_value", "revenue"],
        "formula": "enterprise_value / revenue",
        "metric_type": "cash_flow",
        "metric_description": "Enterprise Value to Sales ratio; indicates company value relative to revenue.",
    },
    # Growth Metrics
    "revenue_change": {
        "inputs": ["revenue_current", "revenue_previous"],
        "formula": "revenue_current - revenue_previous",
        "metric_type": "growth",
        "metric_description": "Absolute change in revenue between periods.",
    },
    "revenue_growth": {
        "inputs": ["revenue", "revenue_previous"],
        "formula": "(revenue - revenue_previous) / revenue_previous",
        "metric_type": "growth",
        "metric_description": "Percentage change in revenue between periods.",
    },
    "eps_change": {
        "inputs": ["eps_current", "eps_previous"],
        "formula": "eps_current - eps_previous",
        "metric_type": "growth",
        "metric_description": "Absolute change in EPS between periods.",
    },
    "eps_growth": {
        "inputs": ["eps", "eps_previous"],
        "formula": "(eps - eps_previous) / eps_previous",
        "metric_type": "growth",
        "metric_description": "Percentage change in EPS between periods.",
    },
    "peg_ratio": {
        "inputs": ["p_e_ratio", "eps_growth"],
        "formula": "p_e_ratio / eps_growth",
        "metric_type": "growth",
        "metric_description": "P/E ratio relative to EPS growth rate; indicates value considering growth.",
    },
    "net_income_change": {
        "inputs": ["net_income_current", "net_income_previous"],
        "formula": "net_income_current - net_income_previous",
        "metric_type": "growth",
        "metric_description": "Absolute change in net income between periods.",
    },
    "net_income_growth": {
        "inputs": ["net_income", "net_income_previous"],
        "formula": "(net_income - net_income_previous) / net_income_previous",
        "metric_type": "growth",
        "metric_description": "Percentage change in net income between periods.",
    },
    "dividend_change": {
        "inputs": ["dividends_current", "dividends_previous"],
        "formula": "dividends_current - dividends_previous",
        "metric_type": "growth",
        "metric_description": "Absolute change in dividends between periods.",
    },
    "dividend_growth": {
        "inputs": ["dividend_change", "dividends_previous"],
        "formula": "dividend_change / dividends_previous",
        "metric_type": "growth",
        "metric_description": "Percentage change in dividends between periods.",
    },
    # Additional Performance Metrics
    "return_on_sales": {
        "inputs": ["ebit", "revenue"],
        "formula": "ebit / revenue",
        "metric_type": "performance",
        "metric_description": "Operating profit as a percentage of sales; indicates operational efficiency.",
    },
    "gross_profit_change": {
        "inputs": ["gross_profit_current", "gross_profit_previous"],
        "formula": "gross_profit_current - gross_profit_previous",
        "metric_type": "performance",
        "metric_description": "Absolute change in gross profit between periods.",
    },
    "gross_profit_growth": {
        "inputs": ["gross_profit_change", "gross_profit_previous"],
        "formula": "gross_profit_change / gross_profit_previous",
        "metric_type": "performance",
        "metric_description": "Percentage change in gross profit between periods.",
    },
    "cash_return_on_assets": {
        "inputs": ["operating_cash_flow", "average_total_assets"],
        "formula": "operating_cash_flow / average_total_assets",
        "metric_type": "performance",
        "metric_description": "Cash-based return on assets; indicates asset efficiency in generating cash.",
    },
    "ocf_minus_capex": {
        "inputs": ["operating_cash_flow", "capex"],
        "formula": "operating_cash_flow - capex",
        "metric_type": "performance",
        "metric_description": "Operating cash flow less capital expenditures; used in FCFE calculation.",
    },
    "fcfe": {
        "inputs": ["ocf_minus_capex", "net_borrowings"],
        "formula": "ocf_minus_capex + net_borrowings",
        "metric_type": "performance",
        "metric_description": "Free Cash Flow to Equity; cash available to equity holders.",
    },
    "free_cash_flow_per_share": {
        "inputs": ["free_cash_flow", "shares_outstanding"],
        "formula": "free_cash_flow / shares_outstanding",
        "metric_type": "performance",
        "metric_description": "Free cash flow allocated to each outstanding share.",
    },
    "fcf_yield": {
        "inputs": ["free_cash_flow_per_share", "share_price"],
        "formula": "free_cash_flow_per_share / share_price",
        "metric_type": "performance",
        "metric_description": "Free cash flow return relative to share price.",
    },
    "dupont_roe": {
        "inputs": ["net_profit_margin", "asset_turnover", "equity_multiplier"],
        "formula": "net_profit_margin * asset_turnover * equity_multiplier",
        "metric_type": "performance",
        "metric_description": "Detailed breakdown of ROE into operational efficiency, asset use efficiency, and leverage.",
    },
}
