id: contra_items_demo
name: Contra Items Demonstration
description: Financial statement demonstrating contra item handling

sections:
  # ASSETS SECTION with Contra Item
  - id: assets_section
    name: Assets
    items:
      - id: gross_ppe_item
        name: Property, Plant & Equipment (Gross)
        type: line_item
        node_id: gross_ppe
        sign_convention: 1
        
      - id: accumulated_depreciation_item
        name: "Less: Accumulated Depreciation"
        type: line_item
        node_id: accumulated_depreciation
        sign_convention: -1
        is_contra: true
        
      - id: net_ppe_item
        name: Property, Plant & Equipment (Net)
        type: line_item
        node_id: net_ppe
        sign_convention: 1

  # LIABILITIES SECTION with Contra Item
  - id: liabilities_section
    name: Liabilities
    items:
      - id: gross_debt_item
        name: Gross Debt
        type: line_item
        node_id: gross_debt
        sign_convention: 1
        
      - id: debt_discount_item
        name: "Less: Debt Discount"
        type: line_item
        node_id: debt_discount
        sign_convention: -1
        is_contra: true
        
      - id: net_debt_item
        name: Net Debt
        type: line_item
        node_id: net_debt
        sign_convention: 1

  # REVENUE SECTION with Contra Items
  - id: revenue_section
    name: Revenue
    items:
      - id: gross_revenue_item
        name: Gross Revenue
        type: line_item
        node_id: gross_revenue
        sign_convention: 1
        
      - id: sales_returns_item
        name: "Less: Sales Returns"
        type: line_item
        node_id: sales_returns
        sign_convention: -1
        is_contra: true
        
      - id: sales_discounts_item
        name: "Less: Sales Discounts"
        type: line_item
        node_id: sales_discounts
        sign_convention: -1
        is_contra: true
        
      - id: net_revenue_item
        name: Net Revenue
        type: line_item
        node_id: net_revenue
        sign_convention: 1 