
id: income_statement
name: Income Statement
description: Reports financial performance over a specific period.
sections:
  - id: revenue_section
    name: Revenue
    items:
      - id: revenue
        name: Total Revenue
        type: line_item
        node_id: Revenue # Maps to the node ID in the graph
        sign_convention: 1
  - id: cost_of_goods_sold
    name: Cost of Goods Sold
    items:
      - id: cogs
        name: Cost of Goods Sold
        type: line_item
        node_id: COGS
        sign_convention: -1 # Often shown as negative or subtracted
  - id: gross_profit_section # Section ID
    name: Gross Profit # Section name
    items:
      - id: gross_profit # Item ID
        name: Gross Profit
        type: metric
        metric_id: gross_profit
        inputs:
          revenue: revenue
          cost_of_goods_sold: cogs
        sign_convention: 1
  - id: operating_expenses
    name: Operating Expenses
    items:
      - id: r_d
        name: Research & Development
        type: line_item
        node_id: R&D
        sign_convention: -1
      - id: sg_a
        name: Selling, General & Administrative
        type: line_item
        node_id: SG&A
        sign_convention: -1
      - id: depreciation_amortization
        name: Depreciation & Amortization
        type: line_item
        node_id: D&A
        sign_convention: -1
    subtotal:
      id: total_operating_expenses
      name: Total Operating Expenses
      type: subtotal
      items_to_sum: [r_d, sg_a, depreciation_amortization]
      sign_convention: -1
  - id: ebitda_section
    name: EBITDA
    items:
      - id: ebitda
        name: EBITDA
        type: calculated
        calculation:
          type: addition
          inputs: [gross_profit, r_d, sg_a]
        sign_convention: 1
  - id: operating_income_section
    name: Operating Income
    items:
      - id: operating_income
        name: Operating Income (EBIT)
        type: calculated
        calculation:
          type: addition # OpInc = Gross Profit + Total Operating Expenses (which is negative)
          inputs: [gross_profit, total_operating_expenses]
        sign_convention: 1
  - id: interest_expense_section
    name: Interest Expense
    items:
      - id: interest_expense
        name: Interest Expense
        type: line_item
        node_id: Interest Expense
        sign_convention: -1 # Shown as negative
  - id: ebt_section
    name: Earnings Before Tax (EBT)
    items:
      - id: ebt
        name: Earnings Before Tax
        type: calculated
        calculation:
          type: addition # EBT = Operating Income + Interest Expense (which is negative)
          inputs: [operating_income, interest_expense]
        sign_convention: 1
  - id: taxes_section
    name: Income Tax Expense
    items:
      - id: taxes
        name: Income Tax Expense
        type: line_item
        node_id: Taxes
        sign_convention: -1 # Shown as negative
  - id: net_income_section
    name: Net Income
    items:
      - id: net_income
        name: Net Income
        type: calculated
        calculation:
          type: addition # Net Income = EBT + Taxes (which is negative)
          inputs: [ebt, taxes]
        sign_convention: 1
