id: test_statement
name: Integrated Financial Statement (Example)
description: Example statement combining key Balance Sheet and Income Statement items used in the example script.

sections:
  # --- Balance Sheet Sections ---
  - id: current_assets
    name: Current Assets
    items:
      - id: cash_and_equivalents
        name: Cash & Equivalents
        type: line_item
        node_id: cash_and_equivalents
        sign_convention: 1
      - id: accounts_receivable
        name: Accounts Receivable
        type: line_item
        node_id: accounts_receivable
        sign_convention: 1
    subtotal:
      id: total_current_assets
      name: Total Current Assets
      type: subtotal
      items_to_sum: [cash_and_equivalents, accounts_receivable]
      sign_convention: 1

  - id: non_current_assets
    name: Non-Current Assets
    items:
      - id: property_plant_equipment
        name: Property, Plant & Equipment
        type: line_item
        node_id: property_plant_equipment
        sign_convention: 1

  - id: total_assets_section
    name: Total Assets
    items:
      - id: total_assets
        name: Total Assets
        type: calculated
        calculation:
          type: addition
          inputs: [total_current_assets, property_plant_equipment]
        sign_convention: 1

  - id: current_liabilities
    name: Current Liabilities
    items:
      - id: accounts_payable
        name: Accounts Payable
        type: line_item
        node_id: accounts_payable
        sign_convention: 1

  - id: non_current_liabilities
    name: Non-Current Liabilities
    items:
      - id: total_debt
        name: Total Debt
        type: line_item
        node_id: total_debt
        sign_convention: 1

  - id: total_liabilities_section
    name: Total Liabilities
    items:
      - id: total_liabilities
        name: Total Liabilities
        type: calculated
        calculation:
          type: addition
          inputs: [accounts_payable, total_debt]
        sign_convention: 1

  - id: equity
    name: Equity
    items:
      - id: common_stock
        name: Common Stock
        type: line_item
        node_id: common_stock
        sign_convention: 1
      - id: prior_retained_earnings
        name: Prior Retained Earnings
        type: line_item
        node_id: prior_retained_earnings
        sign_convention: 1
      - id: dividends
        name: Dividends
        type: line_item
        node_id: dividends
        sign_convention: -1
    subtotal:
      id: total_equity
      name: Total Equity
      type: subtotal
      items_to_sum: [common_stock, prior_retained_earnings, dividends]
      sign_convention: 1

  - id: total_liabilities_equity_section
    name: Total Liabilities & Equity
    items:
      - id: total_liabilities_equity
        name: Total Liabilities & Equity
        type: calculated
        calculation:
          type: addition
          inputs: [total_liabilities, total_equity]
        sign_convention: 1

  # --- Income Statement Section ---
  - id: income_statement
    name: Income Statement
    items:
      - id: revenue
        name: Revenue
        type: line_item
        node_id: revenue
        sign_convention: 1
      - id: cost_of_goods_sold
        name: Cost of Goods Sold
        type: line_item
        node_id: cost_of_goods_sold
        sign_convention: -1
      - id: gross_profit
        name: Gross Profit
        type: calculated
        calculation:
          type: addition
          inputs: [revenue, cost_of_goods_sold]
        sign_convention: 1
      - id: operating_expenses
        name: Operating Expenses
        type: line_item
        node_id: operating_expenses
        sign_convention: -1
      - id: operating_income
        name: Operating Income
        type: calculated
        calculation:
          type: addition
          inputs: [gross_profit, operating_expenses]
        sign_convention: 1
      - id: interest_expense
        name: Interest Expense
        type: line_item
        node_id: interest_expense
        sign_convention: -1
      - id: income_before_tax
        name: Income Before Tax
        type: calculated
        calculation:
          type: addition
          inputs: [operating_income, interest_expense]
        sign_convention: 1
      - id: income_tax
        name: Income Tax
        type: line_item
        node_id: income_tax
        sign_convention: -1
      - id: net_income
        name: Net Income
        type: calculated
        calculation:
          type: addition
          inputs: [income_before_tax, income_tax]
        sign_convention: 1 