income_statement:
  - revenue
  - total_revenue
  - cost_of_goods_sold
  - gross_profit
  - operating_expenses
  - operating_income
  - other_income
  - interest_expense
  - interest_income
  - income_before_taxes
  - income_tax
  - net_income

balance_sheet:
  - cash_and_equivalents
  - short_term_investments
  - accounts_receivable
  - inventory
  - current_assets
  - property_plant_equipment
  - long_term_investments
  - intangible_assets
  - total_assets
  - accounts_payable
  - short_term_debt
  - current_liabilities
  - long_term_debt
  - total_liabilities
  - common_stock
  - retained_earnings
  - total_equity
  - total_liabilities_and_equity

cash_flow:
  - net_income
  - depreciation_amortization
  - changes_in_working_capital
  - cash_from_operating_activities
  - capital_expenditures
  - investments
  - cash_from_investing_activities
  - debt_issuance
  - debt_repayment
  - dividends
  - share_repurchases
  - cash_from_financing_activities
  - net_change_in_cash 