id: test_statement_full
name: "Full Test Statement"
description: "A more comprehensive test statement for validation purposes."
metadata:
  version: "1.1"
  author: "Test User"
sections:
  - id: assets
    type: section
    name: "Assets"
    description: "Represents the company's assets."
    items:
      - id: cash
        type: line_item
        name: "Cash and Cash Equivalents"
        node_id: core.cash
        sign_convention: 1
      - id: ar
        type: line_item
        name: "Accounts Receivable"
        node_id: core.accounts_receivable
        sign_convention: 1
      - id: current_assets_subtotal
        type: subtotal
        name: "Total Current Assets"
        items_to_sum:
          - cash
          - ar
        sign_convention: 1
      - id: ppe
        type: line_item
        name: "Property, Plant & Equipment"
        node_id: core.ppe
        sign_convention: 1
      - id: total_assets
        type: calculated
        name: "Total Assets"
        calculation:
          type: addition
          inputs:
            - current_assets_subtotal
            - ppe
        sign_convention: 1

  - id: liabs_equity
    type: section
    name: "Liabilities & Equity"
    description: "Represents the company's liabilities and owner's equity."
    items: [] # Top-level items can be empty if only subsections are used
    subsections:
      - id: liabilities
        type: section
        name: "Liabilities"
        items:
          - id: ap
            type: line_item
            name: "Accounts Payable"
            node_id: core.accounts_payable
            sign_convention: 1
          - id: debt
            type: line_item
            name: "Long-Term Debt"
            node_id: core.debt
            sign_convention: 1
          - id: total_liabilities
            type: subtotal
            name: "Total Liabilities"
            calculation: # Using calculation instead of items_to_sum
              type: addition
              inputs:
                - ap
                - debt
            sign_convention: 1
      - id: equity
        type: section
        name: "Equity"
        items:
          - id: common_stock
            type: line_item
            name: "Common Stock"
            node_id: core.common_stock
            sign_convention: 1
          - id: retained_earnings
            type: metric
            name: "Retained Earnings"
            metric_id: retained_earnings
            inputs:
              prior_retained_earnings: core.prior_retained_earnings
              net_income: net_income
              dividends: core.dividends
            sign_convention: 1
          - id: total_equity
            type: subtotal
            name: "Total Equity"
            items_to_sum:
              - common_stock
              - retained_earnings
            sign_convention: 1
    subtotal: # Subtotal for the parent 'liabs_equity' section
      id: total_liabs_equity
      type: subtotal
      name: "Total Liabilities & Equity"
      calculation:
        type: addition
        inputs:
          - total_liabilities
          - total_equity
      sign_convention: 1

  # Added an Income Statement section to provide inputs for metrics like Retained Earnings
  - id: income_statement
    type: section
    name: "Income Statement Items (for reference)"
    items:
      - id: revenue
        type: line_item
        name: "Revenue"
        node_id: core.revenue
      - id: cogs
        type: line_item
        name: "Cost of Goods Sold"
        node_id: core.cogs
        sign_convention: -1 # Often negative
      - id: gross_profit
        type: metric
        name: "Gross Profit"
        metric_id: gross_profit
        inputs:
          revenue: revenue
          cost_of_goods_sold: cogs
      - id: opex
        type: line_item
        name: "Operating Expenses"
        node_id: core.opex
        sign_convention: -1 # Often negative
      - id: net_income
        type: calculated
        name: "Net Income"
        calculation:
          type: subtraction
          inputs:
            - gross_profit
            - opex 