id: income_statement_with_adjustments
name: Income Statement with Declarative Adjustments
description: Example demonstrating declarative adjustment handling at item and section levels
metadata:
  version: "1.0"
  purpose: "Demonstrate adjustment filter configuration"

sections:
  # Revenue section with section-level filter for all budget adjustments
  - id: revenue_section
    name: Revenue
    description: Top-line revenue items
    # All items in this section will show budget adjustments by default
    default_adjustment_filter:
      include_tags: ["budget", "forecast"]
      exclude_tags: ["preliminary"]
    items:
      - type: line_item
        id: gross_revenue
        name: Gross Revenue
        node_id: revenue_gross
        description: Total gross revenue before deductions
        # Inherits section filter: shows budget/forecast, excludes preliminary
        
      - type: line_item
        id: revenue_deductions
        name: Revenue Deductions
        node_id: revenue_deductions
        description: Returns, allowances, and discounts
        sign_convention: -1
        # Override section filter to show only actuals
        default_adjustment_filter: []  # No adjustments - actuals only
        
      - type: calculated
        id: net_revenue
        name: Net Revenue
        description: Gross revenue minus deductions
        calculation:
          type: subtraction
          inputs: ["gross_revenue", "revenue_deductions"]
        # Uses section filter by inheritance

  # Cost section with different adjustment strategy
  - id: cost_section
    name: Cost of Goods Sold
    description: Direct costs
    # Show approved adjustments only for cost items
    default_adjustment_filter:
      include_tags: ["approved"]
      include_scenarios: ["base", "conservative"]
    items:
      - type: line_item
        id: material_costs
        name: Material Costs
        node_id: cogs_materials
        description: Raw material and component costs
        # Inherits section filter: approved adjustments only
        
      - type: line_item
        id: labor_costs
        name: Direct Labor
        node_id: cogs_labor
        description: Direct labor costs
        # Override to show management estimates
        default_adjustment_filter:
          include_tags: ["management", "estimate"]
          period: "2024Q4"
        
      - type: calculated
        id: total_cogs
        name: Total Cost of Goods Sold
        description: Sum of all direct costs
        calculation:
          type: addition
          inputs: ["material_costs", "labor_costs"]
        # Uses section filter: approved adjustments

  # Operating expenses with mixed adjustment approaches
  - id: opex_section
    name: Operating Expenses
    description: Operating expenses with various adjustment strategies
    items:
      - type: line_item
        id: salaries
        name: Salaries and Benefits
        node_id: opex_salaries
        description: Employee compensation
        # Item-specific filter for HR planning
        default_adjustment_filter:
          include_scenarios: ["hr_plan", "budget"]
          include_tags: ["approved", "hr"]
          
      - type: line_item
        id: marketing
        name: Marketing Expenses
        node_id: opex_marketing
        description: Marketing and advertising costs
        # Simple tag-based filter
        default_adjustment_filter: ["budget", "marketing_plan"]
        
      - type: line_item
        id: rent
        name: Rent and Facilities
        node_id: opex_rent
        description: Facility costs
        # No adjustments - use actuals only
        default_adjustment_filter: []
        
      - type: calculated
        id: total_opex
        name: Total Operating Expenses
        description: Sum of all operating expenses
        calculation:
          type: addition
          inputs: ["salaries", "marketing", "rent"]
        # No default filter specified - will use no adjustments

  # Special section demonstrating complex filters
  - id: adjustments_section
    name: Special Adjustments
    description: Section showing different adjustment scenarios
    # Complex filter with multiple criteria
    default_adjustment_filter:
      include_scenarios: ["management", "board"]
      exclude_scenarios: ["regulatory"]
      include_tags: ["one_time", "special"]
      exclude_tags: ["error", "duplicate"]
      include_types: ["additive", "replacement"]
      require_all_tags: ["approved"]
    items:
      - type: line_item
        id: one_time_gains
        name: One-time Gains
        node_id: special_gains
        description: Non-recurring gains
        # Uses complex section filter
        
      - type: line_item
        id: restructuring_costs
        name: Restructuring Costs
        node_id: special_costs
        description: Restructuring and reorganization costs
        sign_convention: -1
        # Override with specific restructuring filter
        default_adjustment_filter:
          include_tags: ["restructuring", "approved"]
          include_scenarios: ["restructuring_plan"]

  # Summary section with calculated items
  - id: summary_section
    name: Summary
    description: Key calculated metrics
    items:
      - type: calculated
        id: gross_profit
        name: Gross Profit
        description: Net revenue minus cost of goods sold
        calculation:
          type: subtraction
          inputs: ["net_revenue", "total_cogs"]
        # Show management view with all approved adjustments
        default_adjustment_filter:
          include_tags: ["approved", "management"]
          exclude_tags: ["preliminary", "draft"]
          
      - type: calculated
        id: operating_income
        name: Operating Income
        description: Gross profit minus operating expenses
        calculation:
          type: subtraction
          inputs: ["gross_profit", "total_opex"]
        # Final numbers - show board-approved adjustments only
        default_adjustment_filter:
          include_scenarios: ["board_approved"]
          include_tags: ["final", "approved"]
          require_all_tags: ["board_reviewed"] 