name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Install Nox
        run: |
          python -m pip install --upgrade pip
          pip install nox

      - name: Run Nox "lint" session (ruff, mypy, pytest)
        run: nox -s lint

  perf-security:
    name: Perf & Security Tests
    runs-on: ubuntu-latest
    needs: build-test-lint
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Install dependencies (project + dev extras)
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Run perf & security test subset
        run: pytest -q -m "perf or security" --maxfail=1 