name: Docs CI

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write  # allow push to gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      PYTHONUTF8: 1

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python (pin to 3.12 for library compatibility)
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install project and documentation dependencies
        run: |
          python -m pip install --upgrade pip
          # Install the project in editable mode with dev extras to pull in runtime deps like pydantic
          pip install -e ".[dev]"
          # Documentation tooling (some already included via dev extras)
          pip install pdoc3 "mkdocs>=1.6.1" "mkdocs-material>=9.6.14" "mkdocstrings[python]>=0.29.1"

      - name: Regenerate pdoc HTML
        run: |
          pdoc --html fin_statement_model --output-dir docs/pdoc --force

      - name: Build MkDocs site
        run: mkdocs build --strict

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          # Delete existing files in gh-pages before publishing
          force_orphan: true 